sudo: false
language: python
dist: xenial

install: 
  - pip install tox-travis

stages:
- lints
- test

script: tox
  python:
    - "3.5"
    - "3.6"
    - "3.7"
    
jobs:
  include:
    - stage: lints
      script: tox -c tox.ini -e pep8
      python:
        - "3.5"
        - "3.6"
        - "3.7"

git:
  depth: 10